### ISSUE TITLE
can it support archive debian

### ISSUE THREAD

**Issue by yimiaoxiehou** [thetredev/xdeb-install#20]
i want to download some deb on debian 8.9, can it support.

**Comment by thetredev** [comment]
`xdeb-install` generally only supports active repositories, see https://github.com/xdeb-org/xdeb-install-repositories

You can try to download your DEB file and install it manually. Either directly via `xdeb` or this way: https://github.com/xdeb-org/xdeb-install?tab=readme-ov-file#directly-from-a-local-file

**Comment by yimiaoxiehou** [comment]
thanks
